update makefile
lambdaclass/zksync_seaport pull request #13
Opened 2023-11-08 20:53 UTC by daphneherlambda

Closes #9 
This Pr adds steps in makefile to compile the project

2023-11-08 21:38 UTC, fkrause98 commented
Looks good, but let's merge #10 first and adapt it here.

2023-11-08 21:51 UTC, jpcenteno requested changes

2023-11-08 21:51 UTC, jpcenteno commented on Makefile
> +setup-execution-helper:
IMHO, I would have these separated as different tasks. This is doing 3 distinct things

2023-11-08 21:51 UTC, jpcenteno commented on Makefile
> +setup-seaport:
Separate the setup from the compile steps

2023-11-09 15:09 UTC, fkrause98 commented on Makefile
> +	cd ExecutionHelper && yarn hardhat compile && yarn hardhat deploy-zksync --script deploy.ts
I wanted to reference this line

2023-11-09 16:55 UTC, jpcenteno commented
- ✅ I was able to check that `make setup` works in a recently cloned repo.
- **TODO**  I haven't tested the `make run` command yet. Let me check that.

The code looks good to me. I would like to propose some improvements, which I can provide in another PR if you like.

2023-11-09 16:56 UTC, jpcenteno commented on Makefile
>  .PHONY: setup update run
We should remove this line and mark each one of the targets as PHONY

2023-11-09 17:00 UTC, jpcenteno commented
**WAIT**

I tried to run calling `make run` first instead the `era-test-node` instance that I have running in the background at all times. This failed because it required to run `make setup` first, which depends on having the `era-test-node` running.

I'm going to make a PR pointing to this one with my suggested solution.

2023-11-09 18:27 UTC, fkrause98 approved these changes

2023-11-09 18:47 UTC, jpcenteno approved these changes
LGTM. Doing a follow-up PR #15

2023-11-09 18:47 UTC, merged